import {enabled} from "./helpers.js";

export function createTransferSection(options) {
    return {
        value: "transfer",
        title: "转存设置",
        icon: "mdi-cloud-download-outline",
        groups: [
            {
                title: "订阅范围",
                icon: "mdi-filter-outline",
                fields: [
                    {
                        key: "subscribe_filter_mode",
                        label: "订阅筛选模式",
                        type: "select",
                        items: [
                            {title: "排除所选订阅", value: "exclude"},
                            {title: "仅处理所选订阅", value: "include"},
                        ],
                        cols: 4,
                    },
                    {
                        key: "exclude_subscribes",
                        label: "排除订阅",
                        type: "select",
                        items: options.subscribes,
                        multiple: true,
                        cols: 8,
                        show: (config) => config.subscribe_filter_mode === "exclude",
                    },
                    {
                        key: "include_subscribes",
                        label: "指定订阅",
                        type: "select",
                        items: options.subscribes,
                        multiple: true,
                        cols: 8,
                        show: (config) => config.subscribe_filter_mode === "include",
                    },
                ],
            },
            {
                title: "转存控制",
                icon: "mdi-tune-variant",
                fields: [
                    {
                        key: "cross_transfer_enabled",
                        label: "跨盘资源自动转存",
                        type: "switch",
                        hint: "资源链接与目标网盘不一致时，自动尝试秒传；未命中则进行普通中继上传。任务统一显示在订阅任务中。",
                        cols: 4,
                    },
                    {
                        key: "skip_other_season_dirs",
                        label: "跳过其他季目录",
                        type: "switch",
                        hint: "与目标季数不一致的文件自动跳过。",
                        cols: 8,
                    },
                    {
                        key: "cross_transfer_info",
                        type: "info",
                        label: "跨盘秒传说明",
                        lines: [
                            "仅当资源链接所属网盘与当前目标网盘不一致时触发；同盘资源继续使用原生分享转存。",
                            "115 使用 SHA1；123、光鸭、天翼使用 MD5。只有源文件校验和与目标算法一致时才尝试秒传。",
                            "秒传未命中或源端缺少可用校验和时，自动下载到本地缓存并普通上传；成功后清理，失败或取消时保留以便恢复。",
                            "任务统一显示在订阅任务中，并区分校验、秒传、源盘下载、目标盘上传、完成、失败和取消状态。",
                        ],
                        cols: 12,
                        show: enabled("cross_transfer_enabled"),
                    },
                    {
                        key: "max_transfer_per_sync",
                        label: "单次最大转存文件数",
                        type: "number",
                        min: 1,
                        cols: 4,
                    },
                    {
                        key: "subscription_concurrency",
                        label: "订阅并发数",
                        type: "number",
                        min: 1,
                        max: 5,
                        cols: 4,
                    },
                    {
                        key: "batch_size",
                        label: "分享转存每批数量",
                        type: "number",
                        min: 1,
                        cols: 4,
                    },
                    {
                        key: "batch_interval",
                        label: "转存批次间隔（秒）",
                        type: "number",
                        min: 0,
                        max: 60,
                        cols: 4,
                    },
                    {
                        key: "transfer_risk_cooldown",
                        label: "转存风控冷却（秒）",
                        type: "number",
                        min: 60,
                        max: 86400,
                        cols: 4,
                    },
                ],
            },
            {
                title: "本地路径与 STRM",
                icon: "mdi-folder-play-outline",
                hint: "配置本地媒体根路径及转存后的 STRM 生成方式。",
                fields: [
                    {
                        key: "local_resource_path",
                        label: "本地媒体根路径",
                        placeholder: "/strm",
                        cols: 4,
                    },
                    {
                        key: "cross_transfer_download_path",
                        label: "跨盘中继缓存目录",
                        placeholder: "留空使用系统临时目录",
                        hint: "填写容器内本地绝对路径或已挂载目录。成功后自动清理；失败或取消时保留缓存，可从历史记录恢复。",
                        cols: 6,
                        show: enabled("cross_transfer_enabled"),
                    },
                    {
                        key: "cross_transfer_download_threads",
                        label: "下载线程数",
                        type: "number",
                        min: 1,
                        max: 10,
                        hint: "单个跨盘文件的 Range 并发线程数，默认 5，最大 10。",
                        cols: 2,
                        show: enabled("cross_transfer_enabled"),
                    },
                    {
                        key: "cross_transfer_max_concurrent",
                        label: "同时跨盘任务数",
                        type: "number",
                        min: 1,
                        max: 10,
                        hint: "同时运行的跨盘转存任务数，默认 2。",
                        cols: 4,
                        show: enabled("cross_transfer_enabled"),
                    },
                    {
                        key: "cross_transfer_media_types",
                        label: "允许跨盘转存类型",
                        type: "select",
                        items: [
                            {title: "电影", value: "movie"},
                            {title: "电视剧", value: "tv"},
                        ],
                        multiple: true,
                        hint: "只对选中的媒体类型执行跨盘转存；默认电影和电视剧。",
                        show: enabled("cross_transfer_enabled"),
                    },
                    {
                        key: "strm_generate_enabled",
                        label: "转存后直接生成 STRM",
                        type: "switch",
                        cols: 4,
                    },
                    {
                        key: "nfo_scrape_enabled",
                        type: "switch",
                        label: "刮削生成 NFO",
                        cols: 4,
                    },
                    {
                        key: "image_scrape_enabled",
                        type: "switch",
                        label: "刮削生成图片",
                        cols: 4,
                    },
                    {
                        key: "strm_base_url",
                        label: "STRM 基础地址",
                        placeholder: "http://172.17.0.1:9527",
                        cols: 8,
                        show: enabled("strm_generate_enabled"),
                    },
                    {
                        key: "strm_url_template",
                        label: "STRM URL 模板",
                        type: "textarea",
                        hint: "115变量：{pickcode}；夸克变量：{file_id}；光鸭变量：{file_id}、{gcid}；123变量：{file_id}、{md5}、{size}、{s3_key_flag}；通用变量：{base_url}、{file_name}、{file_path}。插件仅按模板生成 STRM，不代理播放请求。",
                        cols: 12,
                        show: enabled("strm_generate_enabled"),
                    },
                ],
            },
        ]
    }
}
